/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'account': RouteRecordInfo<'account', '/account', Record<never, never>, Record<never, never>>,
    'exchanges': RouteRecordInfo<'exchanges', '/exchanges', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'sample': RouteRecordInfo<'sample', '/sample', Record<never, never>, Record<never, never>>,
    'settings-config': RouteRecordInfo<'settings-config', '/settings/config', Record<never, never>, Record<never, never>>,
    'settings-permission': RouteRecordInfo<'settings-permission', '/settings/permission', Record<never, never>, Record<never, never>>,
    'settings-role': RouteRecordInfo<'settings-role', '/settings/role', Record<never, never>, Record<never, never>>,
    'test': RouteRecordInfo<'test', '/test', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'verify': RouteRecordInfo<'verify', '/verify', Record<never, never>, Record<never, never>>,
  }
}
